version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./DBMS_project:/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"  # Set your MySQL root password here
      MYSQL_DATABASE: "test"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "12345"  # Set the same password as MySQL
